# Generated by Django 6.1.1 on 2026-09-22 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='height',
            field=models.FloatField(default=300, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='chart',
            name='width',
            field=models.FloatField(default=400, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
