# Generated by Django 6.1.1 on 2026-09-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_sharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
